import {
  Sun,
  Moon,
  Laptop,
  Github,
  Twitter,
  Mail,
  ArrowRight,
  CheckCircle2,
  CreditCard,
  LineChart,
  Bell,
  Shield,
  Zap,
  Sparkles,
  TrendingUp,
  Wallet,
  Users,
  Lock,
  Globe,
  Menu,
  LogOut,
  Loader,
  Chrome,
  ChevronRight,
} from "lucide-react"

export const Icons = {
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  gitHub: Github,
  twitter: Twitter,
  mail: Mail,
  arrowRight: ArrowRight,
  checkCircle: CheckCircle2,
  creditCard: CreditCard,
  lineChart: LineChart,
  bell: Bell,
  shield: Shield,
  zap: Zap,
  sparkles: Sparkles,
  trendingUp: TrendingUp,
  wallet: Wallet,
  users: Users,
  lock: Lock,
  globe: Globe,
  menu: Menu,
  logout: LogOut,
  logo: Globe,
  loader: Loader,
  google: Chrome,
  chevronRight: ChevronRight,
}

export const IconColors = {
  sun: "text-yellow-500",
  moon: "text-gray-500",
  laptop: "text-blue-500",
  gitHub: "text-gray-500",
  twitter: "text-blue-500",
  mail: "text-blue-500",
  arrowRight: "text-blue-500",
  checkCircle: "text-green-500",
  creditCard: "text-blue-500",
  lineChart: "text-blue-500",
  bell: "text-orange-500",
  shield: "text-blue-500",
  zap: "text-yellow-500",
  sparkles: "text-yellow-500",
  trendingUp: "text-green-500",
  wallet: "text-blue-500",
  users: "text-blue-500",
  lock: "text-blue-500",
  globe: "text-blue-500",
  menu: "text-gray-500",
  logout: "text-red-500",
  logo: "text-blue-500",
  loader: "text-gray-500",
  google: "text-blue-500",
  chevronRight: "text-gray-500",
} 